### ISSUE TITLE
Update apt sources on installation

### ISSUE THREAD

**Issue by scaleoutsean** [YasuhiroABE/ub-autoinstall-iso#17]
`country-mirror` may result in faster update speeds later on. (`arches &id002` can probably be removed, but it has no impact on me, so I haven't tried). 

```yaml
autoinstall:
  version: 1
  apt:
    disable_components: []
    fallback: offline-install
    geoip: true
    mirror-selection:
      primary:
      - country-mirror
      - arches: &id001
        - amd64
        - i386
        uri: http://archive.ubuntu.com/ubuntu/
      - arches: &id002
        - s390x
        - arm64
        - armhf
        - powerpc
        - ppc64el
        - riscv64
        uri: http://ports.ubuntu.com/ubuntu-ports
    preserve_sources_list: false
```

Curtin uses `preserve_sources_list` to check if the `uri` may be modified in `etc/apt/sources.list `.
